config/routes.rb
Rails.application.routes.draw do
  
  resources :posts , only: [:index,:create] do
    resource :favorites, only: [:create, :destroy]
    resource :comments, only: [:create, :destroy]
  end
  
  resources :users, only: [:create,:show,:edit,:update]
  get 'users/:id/posts', to: 'users#posts'
  get 'users/:id/favorites', to: 'users#favorites' 

  post 'login', to: 'users#login'
  post 'logout', to: 'users#logout'
  root 'home#top'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :post
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    mount_uploader :image_name, ImageUploader
    validates :content, {presence: true, length: {maximum: 200}}
    validates :user_id,{presence: true}

    belongs_to :user
    has_many :favorites
    has_many :comments

    def favorited_by?(user)
        favorites.where(user_id: user.id).exists?
    end
end

app/models/user.rb
class User < ApplicationRecord
    mount_uploader :image_name, ImageUploader
    validates :name, {presence: true}
    validates :email,{presence: true, uniqueness: true}
    validates :password,{presence: true}

    has_many :posts
    has_many :favorites
    has_many :comments
    has_many :favorite_posts, through: :favorites, source: :post
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_current_user, :set_search
  
  def set_current_user
    @current_user = User.find_by(id: session[:user_id])
  end

  def authenticate_user
    if @current_user == nil
      flash[:error] = "You were not login"
      redirect_to root_path
    end
  end

  def forbid_login_user
    if @current_user
      flash[:error] = "You are already logged in"
      redirect_to posts_path
    end
  end

  def set_search
    @search = Post.ransack(params[:q]) 
    @search_posts = @search.result.page(params[:page]).per(4).order(created_at: :desc)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
  end

  def destroy
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = @current_user.favorites.build(post_id: params[:post_id])
    favorite.save
    redirect_to posts_path
  end

  def destroy
    favorite = Favorite.find_by(post_id: params[:post_id], user_id: @current_user.id)
    favorite.destroy
    redirect_to posts_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :forbid_login_user
  def top
    
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user

  def index
    @posts = Post.page(params[:page]).per(4).order(created_at: :desc)
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = @current_user.id
    if @post.save
      flash[:success] = "Post created"
      redirect_to posts_path
    else
      flash[:error] = "Please do not open the blank
                       <br>Please post within 140 characters"
      @posts = Post.page(params[:page]).per(4).order(created_at: :desc)
      render :index
    end
  end

  private
  def post_params
    params.require(:post).permit(:title,:image_name,:content,:user_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController 
  before_action :forbid_login_user, {only: [:create, :login]}
  
  def create
    @user = User.new(user_params)
      if @user.save
       session[:user_id] = @user.id
       flash[:success] = "User registration completed"
       redirect_to posts_path
      else
       flash[:error] = "Email or username already registered"
       render 'home/top'
      end
  end 

  def posts
    @user = User.find(params[:id])
    @current_user_posts = @user.posts.page(params[:page]).per(4).order(created_at: :desc)
  end

  def favorites
    @user = User.find(params[:id])
    @favorite_posts = @user.favorite_posts.page(params[:page]).per(4).order(created_at: :desc)
  end

  def edit
    @user = User.find_by(id: params[:id])
  end

  def update
      @user = User.find_by(id: params[:id])
    if @user.update(user_params)
      redirect_to posts_path, notice: "Update succeeded"
    else
      render :edit
    end
  end

  def login
      @user = User.find_by(email: params[:email], password: params[:password])
    if @user
      session[:user_id] = @user.id
      redirect_to posts_path, notice: "Login succeeded"
    else
      flash[:error] = "The entered email or password has not been registered"
      render 'home/top'
    end
  end

  def logout
    session[:user_id] = nil
    flash[:notice] = "You were logged out"
    redirect_to root_path
  end

 private
  def user_params
    params.require(:user).permit(:name, :email, :profile, :password, :image_name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/favorites/create.html.erb
<h1>Favorites#create</h1>
<p>Find me in app/views/favorites/create.html.erb</p>

app/views/favorites/destroy.html.erb
<h1>Favorites#destroy</h1>
<p>Find me in app/views/favorites/destroy.html.erb</p>

app/views/home/_login_form.html.erb
<div class="modal fade" id="LoginModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
     <div class="modal-dialog" role="document">
          <div class="modal-content">

                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Login</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>

                <div class="form-horizontal" role="form">
                    <%= form_with url: login_path, local: true do |form| %>
                        <div class="modal-body">             
                            <div class="form-group">
                                <%= form.text_field :email, class: "form-control", placeholder: 'email' %>
                            </div>
                            <div class="form-group">
                                <%= form.text_field :password, class: "form-control", placeholder: 'password' %>
                            </div>  
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <%= form.submit class: 'btn btn-primary', value: 'Send' %>
                        </div>
                    <% end %>
                </div>
                   

　        </div>
     </div>
</div>

app/views/home/_signup_form.html.erb
<div class="modal fade" id="SignUpModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
     <div class="modal-dialog" role="document">
          <div class="modal-content">

                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">SignUp</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="form-horizontal" role="form">
                    <%= form_with model: User.new, local: true do |form| %> 
                        <div class="modal-body">             
                            <div class="form-group">
                                <%= form.text_field :name, class: "form-control", placeholder: 'name' %>
                            </div>
                            <div class="form-group">
                                <%= form.text_field :email, class: "form-control", placeholder: 'email' %>
                            </div>
                            <div class="form-group">
                                <%= form.text_field :password, class: "form-control", placeholder: 'password' %>
                            </div>  
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <%= form.submit class: 'btn btn-primary', value: 'Send' %>
                        </div>
                    <% end %>
                </div>
                   
　        </div>
     </div>
</div>

app/views/home/top.html.erb
<div class="top-main">

    <div class="header-top">
        <div class="header-logo">
            <%=link_to("BookSalon","/")%>
        </div>
    </div>

    <div class="bg-slider">
        <%= render partial: 'login_form' %>
        <%= render partial: 'signup_form' %>
        <div class="top-message">
            <h2>Share a moment of memories</h2>
            <p>Let's remember your memory from nostalgic photos!</p>
            <button type="button" class="btn btn-primary btn-lg bule"  data-toggle="modal" data-target="#LoginModal">Login</button>
            <button type="button" class="btn btn-success btn-lg green"  data-toggle="modal" data-target="#SignUpModal">SignUp</button>
        </div>
    </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookSalon</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" script src="./javascripts/move.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    
  </head>

  <body>
    <% unless flash.empty? %>
          <script type="text/javascript">
            <% flash.each do |f| %>
              <% type = f[0].to_s.gsub('alert','error').gsub('notice','info') %>
              toastr['<%= type %>']('<%= f[1] %>');
            <% end %>
          </script>
    <% end %>
  <%= yield %>
  </body>
</html>

app/views/posts/_favorite.html.erb
<% if post.favorited_by?(@current_user) %> <!-- ログインしているユーザーがファボしたかどうかで分岐 -->
    <p><span>お気に入り解除: </span><%=link_to post.favorites.count, post_favorites_path(post.id), method: :delete %></p>
<% else %>
    <p><span>お気に入り登録: </span><%=link_to post.favorites.count, post_favorites_path(post.id), method: :post %></p>
<% end %>

<p><span>お気に入り数: </span><%= post.favorites.count %></p>

app/views/posts/_header.html.erb
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">

        <a class="navbar-brand brand_rogo" href="/">BookSalon</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <%= link_to "Logout", logout_path, class: 'btn btn-outline-dark', method: :post %>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
                <div class="header_img" data-toggle="modal" data-target="#UserModal">
                    <%= image_tag @current_user.image_name.to_s %>
                </div>
                <%= search_form_for @search, url:posts_path do |form| %>
                    <%= form.text_field :title_or_content_cont, class: "form-control mr-sm-2", placeholder: "Please Keyword..." %>
                    <%= form.submit 'Search', class: "btn btn-outline-success my-2 my-sm-0"%>
                <% end %>
                <button type="button" class="btn btn-outline-primary new_post_bottom" data-toggle="modal" data-target="#exampleModal">NewPost</button>
            </form>
        </div>

    </nav> 
<header>

app/views/posts/_post_form_modal.html.erb
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
     <div class="modal-dialog" role="document">
          <div class="modal-content">

                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">New Post</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>

                    <%= form_with model: Post.new, local: true do |form| %>
                        <div class="modal-body">
                         <div class="form-group">
                               <%= form.label :title, 'Title:' %>
                               <%= form.text_field :title, class: 'form-control'%>
                           </div>
                           <div class="form-group">
                             <div class="field_image">
                              <div id="img_field" onClick="$('#file').click()">
                                <%= image_tag("/pic_images/default_image.jpg") %>
                             </div>
                                <%= form.file_field :image_name, class: "image", style: "display:none;", id: "file"%>
                              </div>
                            </div>            
                            <div class="form-group">
                                <%= form.label :content, 'content:' %>
                                <%= form.text_area :content, class: 'form-control' , rows:3%>
                            </div>
                        </div>
                        <div class="modal-footer">
                          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                          <%= form.submit 'post', class: 'btn btn-primary' %>
                        </div>
                    <% end %>

　        </div>
     </div>
</div>

app/views/posts/_search_result.html.erb
<div class="post_card jscroll">
    <% @search_posts.each do |post| %>   
          <section class="card">
              <div class="card-content">
                  <div class="user">
                    <div class="user_item card-user_image">
                        <%= image_tag post.user.image_name.to_s %>
                        <%= post.user.name %>
                    </div>                    
                  </div>

                  </br> 

                  <p class="post_title">
                    <%= post.title %>
                  </p>

                  <div class="post_image">
                      <%= image_tag post.image_name.to_s %></br>
                  </div>

                  <p class="post_content">
                    <%= simple_format(post.content) %>
                  </p>
                  

                <div class="fav-count">
                    <% if post.favorited_by?(@current_user) %> <!-- ログインしているユーザーがファボしたかどうかで分岐 -->
                        <%=link_to post_favorites_path(post.id), method: :delete do %>
                            <i class="fas fa-thumbs-up like-btn-unlike"></i>
                        <% end %>
                    <% else %>
                        <%=link_to post_favorites_path(post.id), method: :post do %>
                            <i class="fas fa-thumbs-up like-btn"></i>
                        <% end %>
                    <% end %>
                    <%= post.favorites.count %>
                </div>

                <div class="com-count" data-toggle="modal" data-target="#UserModal">
                        <i class="far fa-comment-dots"></i>
                </div>
                
                

                <br>

                <div class="post_time"> 
                    <%= post.created_at %>
                </div>


              </div>
          </section>
    <% end %>
    <%= paginate @search_posts %>
</div>

app/views/posts/_user_profile_modal.html.erb
<div class="modal fade" id="UserModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
     <div class="modal-dialog" role="document">
          <div class="modal-content">

          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">User Profile</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
          </div>

          <div class="container">
               <div class="row">
                    <div class="col-md-6 left_img">
                        <br>
                        <%= image_tag @current_user.image_name.to_s %>
                    </div>
                    <div class="col-md-6 prof_right">
                        <h2><%= @current_user.name %></h2>
                        <%= link_to "favorites: #{@current_user.favorites.count}", "/users/#{@current_user.id}/favorites", class: 'btn btn-outline-dark fav_num' %><br>
                        <%= link_to "posts: #{@current_user.posts.count}", "/users/#{@current_user.id}/posts", class: 'btn btn-outline-dark' %>
                    </div>
               </div>
               <div class="row">
                  <div class="col-md-12 user-bottom">
                     <%= simple_format(@current_user.profile) %>
                     <%= link_to "edit", "/users/#{@current_user.id}/edit", class: 'btn btn-primary' %>
                  </div>
               </div>
          </div>

　        </div>
     </div>
</div>

app/views/posts/index.html.erb
<%= render partial: 'header' %>
<%= render partial: 'user_profile_modal'%>
<%= render partial: 'post_form_modal' %>

<div class="posts-index">
    <div class="container">
        <%= render partial: 'search_result' %>
    </div>
</div>
    

app/views/users/_header_edit.html.erb
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">

        <a class="navbar-brand brand_rogo" href="/">BookSalon</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <%= link_to "Logout", logout_path, class: 'btn btn-outline-dark', method: :post %>
                </li>
            </ul>
        </div>

        <%= link_to "return" , posts_path, class: 'btn btn-outline-dark' %>

    </nav> 
<header>

app/views/users/_login_form.html.erb
<div class="modal fade" id="LoginModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
     <div class="modal-dialog" role="document">
          <div class="modal-content">

                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Login</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>

                <div class="form-horizontal" role="form">
                    <%= form_with url: login_path, local: true do |form| %>
                        <div class="modal-body">             
                            <div class="form-group">
                                <%= form.text_field :email, class: "form-control", placeholder: 'email' %>
                            </div>
                            <div class="form-group">
                                <%= form.text_field :password, class: "form-control", placeholder: 'password' %>
                            </div>  
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <%= form.submit class: 'btn btn-primary', value: 'Send' %>
                        </div>
                    <% end %>
                </div>
                   

　        </div>
     </div>
</div>

app/views/users/_signup_form.html.erb
<div class="modal fade" id="SignUpModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
     <div class="modal-dialog" role="document">
          <div class="modal-content">

                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">SignUp</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="form-horizontal" role="form">
                    <%= form_with model: User.new, local: true do |form| %> 
                        <div class="modal-body">             
                            <div class="form-group">
                                <%= form.text_field :name, class: "form-control", placeholder: 'name' %>
                            </div>
                            <div class="form-group">
                                <%= form.text_field :email, class: "form-control", placeholder: 'email' %>
                            </div>
                            <div class="form-group">
                                <%= form.text_field :password, class: "form-control", placeholder: 'password' %>
                            </div>  
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <%= form.submit class: 'btn btn-primary', value: 'Send' %>
                        </div>
                    <% end %>
                </div>
                   
　        </div>
     </div>
</div>

app/views/users/edit.html.erb
<%= render partial: 'header_edit' %>
<div class="container">
    <%= form_with model: @user, local: true do |form| %>   
        <div class="row">
            <div class="col-md-4 left_img prof_left">
                <div class="field image">
                    <%= form.label 'thumbnail (Please select image)' %>
                    <div class="field_image">
                        <div id="img_field" onClick="$('#file').click()">
                            <%= image_tag @user.image_name.to_s %>
                        </div>
                            <%= form.file_field :image_name, class: "image", style: "display:none;", id: "file"%>
                    </div>
                </div>
            </div>
            <div class="col-md-8 prof_right">
                <div class="form-group">
                     <%= form.label :name, 'Name' %>
                     <%= form.text_field :name, class: 'form-control' %>
                </div>
                <div class="form-group">
                     <%= form.label :title, 'Email' %>
                     <%= form.text_field :email, class: 'form-control' %>
                </div>
                <div class="form-group">
                    <%= form.label :body, 'Profile' %>
                    <%= form.text_area :profile, class: 'form-control', rows: 6 %>
                </div>
                <%= form.submit 'Save', class: 'btn btn-primary' %>
            </div>
        </div>
    <% end %>
</div>

app/views/users/favorites.html.erb
<%= render partial: 'header_edit' %>
<div class="posts-index">
    <div class="container">

        <div class="post_card jscroll">
            <% @favorite_posts.each do |post| %>   
                <section class="card">
                    <div class="card-content">
                        <div class="user">
                        <div class="user_item card-user_image">
                            <%= image_tag post.user.image_name.to_s %>
                        </div>
                        <p class="user_item">
                            <%= post.user.name %> 
                        </p>
                        </div>
                        </br> 
                        <p class="post_title">
                            <%= post.title %>
                        </p>
                        <div class="post_image">
                            <%= image_tag post.image_name.to_s %></br>
                        </div>
                        <p class="post_content">
                            <%= simple_format(post.content) %>
                        </p>
                        <div class="post_time">
                            <%= post.created_at %>
                        </div>
                    </div>
                </section>
            <% end %>
            <%= paginate @favorite_posts %>
        </div>

    </div>
</div>

app/views/users/posts.html.erb
<%= render partial: 'header_edit' %>
<div class="posts-index">
    <div class="container">

        <div class="post_card jscroll">
            <% @current_user_posts.each do |post| %>   
                <section class="card">
                    <div class="card-content">
                        <div class="user">
                        <div class="user_item card-user_image">
                            <%= image_tag post.user.image_name.to_s %>
                        </div>
                        <p class="user_item">
                            <%= post.user.name %> 
                        </p>
                        </div>
                        </br> 
                        <p class="post_title">
                            <%= post.title %>
                        </p>
                        <div class="post_image">
                            <%= image_tag post.image_name.to_s %></br>
                        </div>
                        <p class="post_content">
                            <%= simple_format(post.content) %>
                        </p>
                        <div class="post_time">
                            <%= post.created_at %>
                        </div>

                    </div>
                </section>
            <% end %>
            <%= paginate @current_user_posts %>
        </div>

    </div>
</div>